name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build and Push
      env:
        DOCKER_BUILDKIT: 1
        DOCKERHUB_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_PASS: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
        docker build -t zetasql-server --cache-from=naoto0822/zetasql-server:latest --build-arg BUILDKIT_INLINE_CACHE=1 .
        docker tag zetasql-server naoto0822/zetasql-server:latest
        docker push naoto0822/zetasql-server:latest

    - name: Slack Notification on Success
      if: success()
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_CHANNEL: zetasql-server-ci
        SLACK_TITLE: Build Success
        SLACK_COLOR: good

    - name: Slack Notification on Failure
      uses: rtCamp/action-slack-notify@v2.0.2
      if: failure()
      env:
        SLACK_CHANNEL: zetasql-server-ci
        SLACK_TITLE: Build Failure
        SLACK_COLOR: danger
